# .gitlab-ci.yml
trigger_binder_build:

    stage: build

    image: docker:latest

    only:
    - master

    variables:
        TARGET_REPO: https://gitlab.com/nhsbsa/insight/shared/coffee-and-coding
        SERVICE_NAME: gl

    script:
        - docker run s-weigand/trigger-mybinder-build $TARGET_REPO $SERVICE_NAME
