stages:
  - build

build-binder:
  stage: build
  script:
    - apk update && apk add curl
    - curl -L --connect-timeout 20 --max-time 900 "https://mybinder.org/v2/gl/nhsbsa%2Finsight%2Fshared%2Fcoffee-and-coding/HEAD"
  only:
    - master
