# .gitlab-ci.yml
trigger_binder_build:

    stage: build

    image: gitlab/dind

    only:
    - master

    variables:
        NO_PUSH: "true"

    script:
        - docker run jupyterhub/repo2docker-action $NO_PUSH
