channels:
  - defaults
  - conda-forge
  - rdonnellyr

dependencies:
# IDE
  - jupyterlab=3.1.12
  - rstudio=1.2.502
# R
  - r-base=4.1.1
  - r-irkernel=1.2
  - r-jsonlite=1.7.2
  - r-ggplot2=3.3.5
  - r-dplyr=1.0.7
  - r-shiny=1.6.0
  - r-crul=1.1.0
  - r-highcharter=0.8.2
  - r-readxl=1.3.1
  - r-shinycssloaders=1.0.0
  - r-shinywidgets=0.6.2
  - r-rgdal=1.5_23
  - r-leaflet=2.0.4
# Python
  - python=3.9.7
  - ipykernel=6.4.1
  - requests=2.26.0
  - pandas=1.3.3
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - numpy=1.21.2
  - statsmodels=0.12.2
  - scikit-learn=1.0.rc2
  - scipy=1.7.1
  
  
