channels:
  - defaults
  - conda-forge

dependencies:
# IDE
  - jupyterlab
# R
  - r-base=4.*
  - r-irkernel
  - r-jsonlite
  - r-ggplot2
  - r-dplyr
# Python
  - python=3.*
  - ipykernel
  - requests
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - statsmodels 
  - scikit-learn
  - scipy
  
  
