channels:
  - defaults
  - conda-forge
  - rdonnelly

dependencies:
# IDE
  - jupyterlab=3.1.7
  - rstudio=1.2.502
# R
  - r-base=3.6.3
  - r-irkernel=1.2
  - r-jsonlite=1.7.2
  - r-ggplot2=3.1.1
  - r-dplyr=0.8.0.1
  - r-shiny=1.3.2
  - r-crul=1.1.0
  - r-highcharter=0.8.2
  - r-readxl=1.3.1
  - r-shinycssloaders=0.2.0
  - r-shinywidgets=0.4.9
  - r-rgdal=1.4
  - r-leaflet=2.0.2
# Python
  - python=3.7.1
  - ipykernel=6.2.0
  - requests=2.26.0
  - pandas=1.3.2
  - matplotlib=3.4.2
  - seaborn=0.11.2
  - numpy=1.20.3
  - statsmodels=0.12.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  
