channels:
  - defaults
  - conda-forge

dependencies:
# IDE
  - jupyterlab
# R
  - r-base=4.*
  - r-irkernel
  - r-jsonlite
  - r-ggplot2
# Python
  - python=3.*
  - ipykernel
  - requests
  - pandas
  - matplotlib
